import { generateMilestones } from "./openai";

export interface BoardResult {
  board_id: string;
  board_url: string;
  milestones: unknown[];
}

export async function createExecutionBoard(
  sessionId: string,
  startupIdea: string,
  recommendedPath: { path_name: string; path_type: string; description: string }
): Promise<BoardResult> {
  const apiKey = process.env.PROJECT_HUB_API_KEY;
  const baseUrl = process.env.PROJECT_HUB_BASE_URL;

  // Always generate AI milestones — used either for real board or fallback
  const milestones = await generateMilestones(startupIdea, recommendedPath).catch(() => []);

  if (!apiKey || !baseUrl) {
    console.warn("Project HUB not configured — returning local board reference");
    return {
      board_id: `local_${sessionId}`,
      board_url: `/venture-twin?session=${sessionId}`,
      milestones,
    };
  }

  try {
    const response = await fetch(`${baseUrl}/boards`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: `VenturePilot — ${recommendedPath.path_name}`,
        description: `Generated by VenturePilot OS for: ${startupIdea}`,
        session_id: sessionId,
        milestones,
        template: "startup_execution",
      }),
    });

    if (!response.ok) {
      throw new Error(`Project HUB API responded with ${response.status}`);
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any = await response.json();

    return {
      board_id: data.id ?? data.board_id ?? `phub_${sessionId}`,
      board_url: data.url ?? data.board_url ?? `/venture-twin?session=${sessionId}`,
      milestones: data.milestones ?? milestones,
    };
  } catch (error) {
    console.error("Project HUB error:", error);
    return {
      board_id: `local_${sessionId}`,
      board_url: `/venture-twin?session=${sessionId}`,
      milestones,
    };
  }
}
